name: website-stalker

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *' # every 15 minutes

permissions:
  contents: write

jobs:
  website-stalker:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_TARGET_CHAT: "-1001631314927"
      TELEGRAM_DISABLE_WEB_PAGE_PREVIEW: true
    steps:
      - uses: EdJoPaTo/website-stalker-github-action@v1

      - uses: actions/checkout@v4

      - name: Run website-stalker
        id: website-stalker
        run: website-stalker run --all --commit

      - if: success() || steps.website-stalker.outcome == 'failure'
        run: git push
