name: website-stalker

on:
  push:
  schedule:
    - cron:  '*/15 * * * *' # every 15 minutes

jobs:
  website-stalker:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_TARGET_CHAT: "-1001631314927"
      TELEGRAM_DISABLE_WEB_PAGE_PREVIEW: true
    steps:
      - uses: actions/checkout@v2

      - name: Run website-stalker
        uses: docker://ghcr.io/edjopato/website-stalker:latest
        with:
          args: run --all --commit

      - if: always()
        run: git push
